services:
    db:
        container_name: postgres_container
        image: postgres:14.17
        ports:
            - 5000:5432
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        networks:
            - my-network
    
    dbt:
        container_name: dbt_container
        image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
        volumes:
            - ./dbt/my_project:/usr/app
            - ./dbt:/root/.dbt
        working_dir: /usr/app
        environment:
            DBT_PROFILES_DIR: "/root/.dbt"
        depends_on:
            - db
        networks:
            - my-network
        command: run

networks:
    my-network:
        driver: bridge
